### PR TITLE
Add support for CentOS Stream containers

### PR DESCRIPTION
**Pull request by danrodrig**
- Added provision scripts for centos:stream8 and centos:stream9 containers
- Fixed static builds for CentOS Stream
- Added CentOS Stream static build in review checks

### CODE REVIEW

**Comment by StykMartin** [comment]
F39 and F40 Valgrind failures are tracked here https://github.com/restraint-harness/restraint/issues/310 - that's fine.
Can you please extend current Packit targets so we can see that this change is doing the magic? https://github.com/restraint-harness/restraint/blob/master/.packit.yaml#L21

Thank you very much!

**Comment by StykMartin** [comment]
Nevermind, this needs to be extended in review checks https://github.com/restraint-harness/restraint/blob/master/.github/workflows/review-checks.yml#L67 as Packit does builds with dynamic linking.

**Comment by danrodrig** [comment]
> Nevermind, this needs to be extended in review checks https://github.com/restraint-harness/restraint/blob/master/.github/workflows/review-checks.yml#L67 as Packit does builds with dynamic linking.

Added. I didn't realize at first that the container images for CentOS Stream aren't available in DockerHub, that's why I added the extra job. Let me know if you have a better way to deal with this.

**Review by StykMartin — APPROVED** [review]

**Comment by StykMartin** [comment]
You can create a more complex matrix, something like a <key, hashmap>, where you would define the source for images and so on, but I don't think we need to do that here, as the pipeline is full of conditions for specific systems anyway, a new job won't do any harm. 

Thanks for fixing this! I didn't realize I could try to rebuild it with older pcre.

**Comment by danrodrig** [comment]
> You can create a more complex matrix, something like a <key, hashmap>, where you would define the source for images and so on, but I don't think we need to do that here, as the pipeline is full of conditions for specific systems anyway, a new job won't do any harm.
> 
> Thanks for fixing this! I didn't realize I could try to rebuild it with older pcre.

Thank you for taking care of the PR! :dolphin:

**Pull request merged**
