### PR TITLE
Plug resource leaks

### PR DESCRIPTION
**Pull request by ernestask**
Not much to say about this, see individual commits. Only compile-tested.

### CODE REVIEW

**Comment by StykMartin** [comment]
@ernestask ref https://github.com/beaker-project/restraint/pull/210 ?

**Review by StykMartin — APPROVED** [review]
I see autoptr I approve.

**Comment by ernestask** [comment]
It’s not really related to #81, as most of this stuff happens on error. It can help marginally, though.

**Comment by StykMartin** [comment]
> It’s not really related to #81, as most of this stuff happens on error. It can help marginally, though.

Well if it doesn't fix 81, you better fix it 👀 🐬

**Review by cbouchar — APPROVED** [review]
Much cleaner. Looks good.

**Comment by cbouchar** [comment]
@ernestask I value your memory leak changes but I'm running solo support at my company so spread a bit thin.  I plan on doing a release soon.  Hoping you could resurrect/rebase this changeset and I will be happy to approve/merge.

**Comment by ernestask** [comment]
I’ve nuked my fork, so I can’t exactly tell how this will go.

**Comment by cbouchar** [comment]
Easiest thing would be to leave this closed and reopen another changeset on latest restraint from new fork.

**Pull request closed without merging**
